

const selecoes = {
  ABK: require('./assets/jogos/abkhazia.png'),
  AFG: require('./assets/jogos/afghanistan.png'),
  ALA: require('./assets/jogos/aland islands.png'),
  ALB: require('./assets/jogos/albania.png'),
  ALG: require('./assets/jogos/Algeria.png'),
  ASA: require('./assets/jogos/american samoa.png'),
  AND: require('./assets/jogos/andorra.png'),
  ANG: require('./assets/jogos/angola.png'),
  AIA: require('./assets/jogos/anguilla.png'),
  ATG: require('./assets/jogos/antigua and barbuda.png'),
  ARG: require('./assets/jogos/argentina.png'),
  ARM: require('./assets/jogos/armenia.png'),
  ARU: require('./assets/jogos/aruba.png'),
  AUS: require('./assets/jogos/australia.png'),
  AUT: require('./assets/jogos/austria.png'),
  AZE: require('./assets/jogos/azerbaijan.png'),
  BEL: require('./assets/jogos/belgium.png'),
  BRA: require('./assets/jogos/brazil.png'),
  CMR: require('./assets/jogos/cameroon.png'),
  CAN: require('./assets/jogos/canada.png'),
  CHI: require('./assets/jogos/chile.png'),
  CHN: require('./assets/jogos/china.png'),
  COL: require('./assets/jogos/colombia.png'),
  CRC: require('./assets/jogos/costa rica.png'),
  CRO: require('./assets/jogos/croatia.png'),
  DEN: require('./assets/jogos/denmark.png'),
  ECU: require('./assets/jogos/ecuador.png'),
  EGY: require('./assets/jogos/egypt.png'),
  ENG: require('./assets/jogos/england.png'),
  FRA: require('./assets/jogos/france.png'),
  GER: require('./assets/jogos/germany.png'),
  GHA: require('./assets/jogos/ghana.png'),
  GRE: require('./assets/jogos/greece.png'),
  HON: require('./assets/jogos/honduras.png'),
  HUN: require('./assets/jogos/hungary.png'),
  IRN: require('./assets/jogos/iran.png'),
  IRL: require('./assets/jogos/ireland.png'),
  ISR: require('./assets/jogos/israel.png'),
  ITA: require('./assets/jogos/italy.png'),
  JPN: require('./assets/jogos/japan.png'),
  KOR: require('./assets/jogos/south korea.png'),
  MAR: require('./assets/jogos/morocco.png'),
  MEX: require('./assets/jogos/mexico.png'),
  NED: require('./assets/jogos/netherlands.png'),
  NGA: require('./assets/jogos/nigeria.png'),
  NOR: require('./assets/jogos/norway.png'),
  PAN: require('./assets/jogos/panama.png'),
  PAR: require('./assets/jogos/paraguay.png'),
  PER: require('./assets/jogos/peru.png'),
  POL: require('./assets/jogos/poland.png'),
  POR: require('./assets/jogos/portugal.png'),
  QAT: require('./assets/jogos/qatar.png'),
  ROU: require('./assets/jogos/romania.png'),
  RUS: require('./assets/jogos/russia.png'),
  KSA: require('./assets/jogos/saudi arabia.png'),
  SEN: require('./assets/jogos/senegal.png'),
  SRB: require('./assets/jogos/serbia.png'),
  RSA: require('./assets/jogos/south africa.png'),
  ESP: require('./assets/jogos/spain.png'),
  SUI: require('./assets/jogos/switzerland.png'),
  TUN: require('./assets/jogos/tunisia.png'),
  TUR: require('./assets/jogos/turkey.png'),
  UKR: require('./assets/jogos/ukraine.png'),
  UAE: require('./assets/jogos/united arab emirates.png'),
  USA: require('./assets/jogos/united states.png'),
  URU: require('./assets/jogos/uruguay.png'),
  CPV: require('./assets/jogos/cape verde.png'),
  NZL: require('./assets/jogos/new zealand.png'),
  CIV: require('./assets/jogos/ivory coast.png'),
  SCO: require('./assets/jogos/scotland.png'),
  CUW: require('./assets/jogos/curacao.png'),
  BIH: require('./assets/jogos/bosnia and herzegovina.png'),
  IRQ: require('./assets/jogos/iraq.png'),
  JOR: require('./assets/jogos/jordan.png'),
  UZB: require('./assets/jogos/uzbekistan.png'),
  COD: require('./assets/jogos/congo.png'),
  HAI: require('./assets/jogos/haiti.png'),
  SWE: require('./assets/jogos/sweden.png'),
  CZE: require('./assets/jogos/czech republic.png'),
};

export const getLogoSelecao = (sigla) => {
  return selecoes[sigla] ?? null;
};

export default selecoes;